{% set name = "mellon" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5731e09d5f82c7f8e3849b12ec9c7dd0b6afbab1a6c70842e99e5d4478954edb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ 3.8 }}
    - pip
    - setuptools
  run:
    - python >={{ 3.8 }}
    - jax
    - jaxopt
    - scikit-learn

test:
  imports:
    - mellon
  commands:
    - pip check
  requires:
    - python {{ 3.8 }}
    - pip

about:
  home: https://github.com/settylab/mellon
  summary: Non-parametric density estimator.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - katosh
    - ManuSetty
