{% set name = "mellon" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12f6f29478f7b98b1b427a4484aca627df4017a47d2c25bda85005aae5434d32

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - jax
    - jaxopt
    - scikit-learn
    - pynndescent

test:
  imports:
    - mellon
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/settylab/mellon
  summary: Non-parametric density estimator.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - katosh
    - ManuSetty
